[project]
name = "suitesparse-amd"
version = "0.1.0"
description = "A Python wrapper for the C-Library for SuiteSparse's Approximate Minimum Degree (AMD) algorithm"
requires-python = ">=3.12"
dependencies = []
